##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [3]:
#pip install numpy

In [4]:
import numpy as np

In [16]:
arr = np.array([12,24.5,7,"56",54/2],dtype="int")
arr

array([12, 24,  7, 56, 27])

In [17]:
print("dizinin boyutu :",arr.ndim)

dizinin boyutu : 1


In [18]:
print("dizinin eleman sayısı :",arr.size)

dizinin eleman sayısı : 5


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [22]:
array2 = np.array([[1,2,6,7], [4,3,9,5]])
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [29]:
print("dizinin boyutu :",array2.ndim)
print("dizinin eleman sayısı :",array2.size)
satir,sutun = np.shape(array2)
print("dizinin satır sayısı : {}".format(satir))
print("dizinin sütun sayısı : {}".format(sutun))

dizinin boyutu : 2
dizinin eleman sayısı : 8
dizinin satır sayısı : 2
dizinin sütun sayısı : 4


In [23]:
array3 = np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [33]:
print("dizinin boyutu :",array3.ndim)
print("dizinin eleman sayısı :",array3.size)
katman,satir,sutun = np.shape(array3)
print("dizinin katman sayısı : {}".format(katman))
print("dizinin satır sayısı : {}".format(satir))
print("dizinin sütun sayısı : {}".format(sutun))

dizinin boyutu : 3
dizinin eleman sayısı : 12
dizinin katman sayısı : 2
dizinin satır sayısı : 2
dizinin sütun sayısı : 3


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [38]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [42]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
array2[0,1]

2

In [43]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
array2[0,-1]

7

In [39]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [44]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
array3[1,1,-1]

9

In [45]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
array3[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [46]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [47]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
array2[0,1:3]

array([2, 6])

In [48]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
array2[1,1:]

array([3, 9, 5])

In [49]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [50]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
array3[0,1]

array([21,  8, 11])

In [51]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
array3[1,0,1:]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [59]:
a = np.zeros((5,3),dtype="int")
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [60]:
b = np.ones((5,3),dtype="int")
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [67]:
c = np.concatenate([a,b],axis=0)
c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
d = np.concatenate([a,b],axis=1)
d

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])